language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov pytest-cov

# command to run tests
before_script: cd email-val
script: pytest -v --cov=./
after_script: codecov
