# Generated by Django 2.0.2 on 2018-02-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('last_validation', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('va', 'Valid'), ('in', 'Invalid'), ('un', 'Unknown'), ('aa', 'Accept all')], max_length=2)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('is_role_address', models.BooleanField(default=False)),
            ],
        ),
    ]
